### ISSUE TITLE
[BUG]: JSON object value not a string or string[]:

### ISSUE THREAD

**Issue by johnfelipe** [desw0lf/node-json-ibm-watson-translator#2]
https://gist.github.com/743bb1a088ebc724828ecb6d624bfb5d

```
root@ubuntu21:~/node-json-ibm-watson-translator# LOCALE_FOLDER=./knowage OUTPUT_LANGUAGES=es node-json-ibm-watson-translator


## 1 ## language to be translated:
es
-

en ==> es
JSON object value not a string or string[]:
{"css":"css","html":"html","javascript":"javascript","python":"python"}
___________________________________
/root/.nvm/versions/node/v16.15.0/lib/node_modules/node-json-ibm-watson-translator/dist/helpers/index-original-data-mapping.js:35
                throw new Error();
                ^

Error
    at Object.entries.reduce.array (/root/.nvm/versions/node/v16.15.0/lib/node_modules/node-json-ibm-watson-translator/dist/helpers/index-original-data-mapping.js:35:23)
    at Array.reduce (<anonymous>)
    at Object.indexOriginalDataMapping (/root/.nvm/versions/node/v16.15.0/lib/node_modules/node-json-ibm-watson-translator/dist/helpers/index-original-data-mapping.js:13:41)
    at /root/.nvm/versions/node/v16.15.0/lib/node_modules/node-json-ibm-watson-translator/dist/main.js:37:64
    at /root/.nvm/versions/node/v16.15.0/lib/node_modules/node-json-ibm-watson-translator/dist/helpers/read-json-file.js:31:9
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

```

**Comment by johnfelipe** [comment]
```
JSON object value not a string or string[]:
{"movecamera":"Move Camera","flyFast":"Fly faster","orbit":"Orbit / Select","pan":"Pan","fly":"Fly","focus":"Focus","rotateLeft":"Rotate Left","rotateRight":"Rotate Right","cancelPlacement":"Cancel Placement","placeDuplicate":"Place Duplicate","cancelGrab":"Cancel Grab","grab":"Grab","deselectAll":"Deselect All"}

```
